version: "3.8"
services:
  postgres-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: